### ISSUE TITLE
Unknown StepExecution throws IllegalArgumentException

### ISSUE THREAD

**Issue by jodidiot** [seedstack/batch-monitoring-function#12]
When a job with unknown StepExecution status is selected, an IllegalArgumentException is thrown.
This can be tested with the internal demo application when selecting Jobs / jobDataTransferCostingFather / 2760 :

```
java.lang.IllegalArgumentException: The entity Id must be provided to re-hydrate an existing StepExecution
    at org.springframework.util.Assert.notNull(Assert.java:112) ~[spring-core-4.1.4.RELEASE.jar:4.1.4.RELEASE]
    at org.seedstack.batch.monitoring.rest.stepexecution.StepExecutionDetailsRepresentation.<init>(StepExecutionDetailsRepresentation.java:134) ~[batch-monitoring-function-rest-2.0.1-SNAPSHOT.jar:na]
    at org.seedstack.batch.monitoring.rest.stepexecution.StepExecutionRepresentation.<init>(StepExecutionRepresentation.java:99) ~[batch-monitoring-function-rest-2.0.1-SNAPSHOT.jar:na]
    at org.seedstack.batch.monitoring.rest.stepexecution.StepExecutionResource.list(StepExecutionResource.java:57) ~[batch-monitoring-function-rest-2.0.1-SNAPSHOT.jar:na]
    at org.seedstack.seed.security.internal.authorization.RequiresPermissionsInterceptor.invoke(RequiresPermissionsInterceptor.java:51) ~[seed-security-support-core-2.0.0.jar:na]
    ...
```

**Comment by jodidiot** [comment]
See pull request https://github.com/seedstack/batch-monitoring-function/pull/13
